### ISSUE TITLE
open download folder while not completed

### ISSUE THREAD

**Issue by tortino** [aesqe/firefox-downloads-sidebar#16] opened 2019-06-29 08:42 UTC
hello,
I'd like to open the download folder even if the download is not completed: usually I open the folder and the drag and drop the url into the folder, to remember the site from which I downloaded the file. Instead noe the icon is disabled during download. Can you just always enable the icon?
thanks.

**Comment by josalhor** [comment] 2019-06-29 09:11
That's actually an interesting behaviour. I didn't design it, aesqe did. My intution was that the folder was not known until the end of the download, so I never fully checked that functionality/code. I also thought it was designed to mimick the way usual downloads work? But that is not that right, since on the official download panel you can right click and open the folder.

Also, anyway the icon can still be clicked even if visually it doesn't look like it. (wuh?)

I'm probably going to pull request this to change.

**Comment by tortino** [comment] 2019-06-29 09:25
ah yes, it's always clickable. doh!

**Comment by aesqe** [comment] 2019-06-30 12:23
Fixed in #17

**Closed by aesqe** 2019-06-30 12:23 UTC
